version: '3.8'

services:
  neo4j:
    image: neo4j:5.16
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/test12345678
    volumes:
      - neo4j_data:/data

  kg_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kg_app
    depends_on:
      - neo4j
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=test12345678
    
    volumes:
      - .:/app

volumes:
  neo4j_data: